namespace MDUA.Framework.Utils
{
    public class Menus
    {
        public enum SelectedNewsMenu
        {
            DashBoard=0,
            News=1,
            WriteANewNews=2,
            AddNewHeadline=3,
            AddItihaserEiDine=4,
            ManageNews=5,
            ManageComments=6,
            ManageHeadline=7,
            ManageBreakingNews=8,
            Ads=9,
            NewAds=10,
            NewTvAds=11,
            NewQuestion=12,
            ManageAds=13,
            ManageTvAds=14,
            ManageQuestion=15,
            ShowVotingStatus=16,
            CreateAlbum=17,
            UploadImage=18,
            ManageGallery=19,
            ManageAlbum=20,
            GallerySettings=21,
            Admin=22,
            NewUser=23,
            ManageUser=24,
            UserPermission=25,
            BannedUser=26,
            Setting=27,
            General=28,
            Design=29,
            ContentUpload = 30,
            DataBackup = 31,
            AddTodaysTvPrograms=32,
            ManageTvPrograms=33,
            ChangePassword = 34,
            ManageTodaysDhaka = 35,
            UserComments= 36,

            NewInstitute = 40,
            MangeInstitute = 41,
            NewLogo = 42,
            ManageLogo = 43,
            NewTestimonial = 44,
            ManageTestimonial = 45,
            NewUniversityVisit = 46,
            ManageUniversityVisit = 47,
            ManageOffice = 48,
            NewCountry = 49,
            ManageCountry = 50,
            NewImageContent = 51,
            ManageImageContent = 52,

            NewNewsEvent = 53,
            ManageNewsEvent = 54,
            NewPresessionalCourse = 55,
            ManagePresessionalCourse = 56,

            Home = 59,
            AboutUs=60,
            Message=61,
            Mission=62,
            Vission=63,
            Guidelines=64,
            Accomodation=65,
            AirportPickup=66,
            CompleteAdmission=67,
            VisaAdmission=68,
            UniversitySelection=69,
            Recomendation = 70,
            TravelAssistance = 71,
            Resources=72
        }
    }
}
