using MDUA.Entities;
using MDUA.Entities.Bases;
using MDUA.Entities.List;
using System.Data.SqlClient; // Required for SqlTransaction

namespace MDUA.DataAccess.Interface
{
    public interface IBulkPurchaseOrderDataAccess
    {
        // 1. Fix: Add the overload that accepts SqlTransaction
        long Insert(BulkPurchaseOrder obj, SqlTransaction trans = null);

        // 2. Fix: Ensure return type matches the Class (BulkPurchaseOrderList, not List<T>)
        BulkPurchaseOrderList GetAll();

        // Include other standard methods generated by your architecture
        BulkPurchaseOrder Get(int id);
        long Update(BulkPurchaseOrderBase obj);
        long Delete(int id);
    }
}